FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

 
COPY ["SaleManagement/SaleManagement.csproj", "SaleManagement/"]
RUN dotnet restore "SaleManagement/SaleManagement.csproj"

 
COPY . .
WORKDIR "/src/SaleManagement"

 
RUN dotnet publish "SaleManagement.csproj" -c Release -o /app/publish

 
 
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS final
WORKDIR /app
COPY --from=build /app/publish .

 
EXPOSE 8080

 
ENV ASPNETCORE_URLS=http://+:8080

 
ENTRYPOINT ["dotnet", "SaleManagement.dll"]